spring.application.name=HostalManagementSystem

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/smartHostalManagementSystm_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# DevTools
spring.devtools.restart.enabled=false

jwt.secret=SmartHostelManagementSystemJWTSecretKeyForAuthentication2026Secure

# ===== NEW: Email (Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bandaradhananjay70@gmail.com
spring.mail.password=ogsuffexpicferkb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend login URL (email eke link ekatt use karanawa)
app.frontend.login-url=http://localhost:5173/login